### ISSUE TITLE
Remove all reference to HDMC from the SPASE Website

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/website#3]
Please remove mention of HDMC from SPASE website. See attached for what to remove.
Location: https://spase-group.org/connect.html#HDMC

![image](https://github.com/spase-group/website/assets/108490588/1007eb22-ee6a-43ca-9e7f-d797bdf48528)

Hi Chuck, please let me know if the image did not come through...
Thank you. Tressa

**Comment by cfdolan** [comment]
I can see the image. Will review.

**Comment by cfdolan** [comment]
Accidentally closed trying to leave a note. Reopening

**Comment by cfdolan** [comment]
The HDMC links are gone but that last link remaining - "SPASE Metadata Working Group" - doesn't go anywhere. Shall I pull that as well?

**Comment by tressahelvey** [comment]
Per Shing   @sffung 

Yes, but we need to modify the descriptive paragraph to:
“… (SMWT) has been formed with the primary objective of applying the SPASE metadata model to document and describe all electronically-accessible heliophysics digital resources sponsored by NASA. Upon request, the SMWT will also assist the community in creating SPASE metadata and managing their SPASE resources.”  Questions about SPASE implementation can be sent to [spase-support@groups.io](mailto:spase-support@groups.io).

**Comment by cfdolan** [comment]
Completed.
