### ISSUE TITLE
Add "Collection" to tree listing and make searchable

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/website#4]
New resource type “Collection” defined in SPASE 2.5.0 is missing the SPASE dictionary tree on https://spase-group.org/data/model/search/index.html.  Searching for the definition of the term Collection also came up empty. Can this be fixed quickly as the SPASE paper actually refers to Collection.

**Comment by cfdolan** [comment]
FWIW if the user clicks on a different version radio button, like 2.4.2 and then back to 2.5.0 then Collection appears. The trick will be figuring out how to make the 2.5.0 branch visible on first look.

**Comment by tressahelvey** [comment]
What is your opinion? Should the issue be fixed before 2.6.0 is released? Thank you.


______________________________
Regards,
Tressa Helvey-Kasulke
NASA/Goddard Space Flight Center
Project Manager, HDRL
Cell: 202-870-4363

From: cfdolan ***@***.***>
Sent: Wednesday, June 21, 2023 12:32 PM
To: spase-group/website ***@***.***>
Cc: Helvey-Kasulke, Tressa L. (GSFC-672.0)[ASRC FEDERAL SYSTEM SOLUTIONS] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [spase-group/website] Add "Collection" to tree listing and make searchable (Issue #4)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



FWIW if the user clicks on a different version radio button, like 2.4.2 and then back to 2.5.0 then Collection appears. The trick will be figuring out how to make the 2.5.0 branch visible on first look.

-

**Comment by cfdolan** [comment]
Fixed already. Hard-to-find config file.

**Comment by cfdolan** [comment]
To test you'll likely need to do a hard refresh of the page (shift-click) to clear out the javascript cache.

**Comment by tressahelvey** [comment]
Issue fixed
